SELECT
    T3.REDIRECT_URL
FROM
    ACCOUNT T1
LEFT JOIN
    ACCOUNT_MAPPING_APPLICATION T2
ON
    T1.ACCOUNT_ID=T2.ACCOUNT_ID
LEFT JOIN
    APPLICATION_SETTING T3
ON
    T2.APP_ID=T3.APP_ID
WHERE
    T3.APP_ID=:APP_ID
AND T1.ACCOUNT_ID=:ACCOUNT_ID