package com.elitech.gate.pojo;
// Generated Nov 8, 2017 2:56:14 PM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccountMappingApplicationId generated by hbm2java
 */
@Embeddable
public class AccountMappingApplicationId  implements java.io.Serializable {


     private String accountId;
     private String appId;

    public AccountMappingApplicationId() {
    }

    public AccountMappingApplicationId(String accountId, String appId) {
       this.accountId = accountId;
       this.appId = appId;
    }
   


    @Column(name="account_id", nullable=false)
    public String getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }


    @Column(name="app_id", nullable=false)
    public String getAppId() {
        return this.appId;
    }
    
    public void setAppId(String appId) {
        this.appId = appId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AccountMappingApplicationId) ) return false;
		 AccountMappingApplicationId castOther = ( AccountMappingApplicationId ) other; 
         
		 return ( (this.getAccountId()==castOther.getAccountId()) || ( this.getAccountId()!=null && castOther.getAccountId()!=null && this.getAccountId().equals(castOther.getAccountId()) ) )
 && ( (this.getAppId()==castOther.getAppId()) || ( this.getAppId()!=null && castOther.getAppId()!=null && this.getAppId().equals(castOther.getAppId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAccountId() == null ? 0 : this.getAccountId().hashCode() );
         result = 37 * result + ( getAppId() == null ? 0 : this.getAppId().hashCode() );
         return result;
   }   


}


