package com.elitech.gate.pojo;
// Generated Nov 8, 2017 2:56:14 PM by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountMappingApplication generated by hbm2java
 */
@Entity
@Table(name="account_mapping_application"
    ,schema="public"
)
public class AccountMappingApplication  implements java.io.Serializable {


     private AccountMappingApplicationId id;
     private String createUser;
     private Date createTime;
     private String modifyUser;
     private Date modifyTime;
     private Date lastlogintime;

    public AccountMappingApplication() {
    }

	
    public AccountMappingApplication(AccountMappingApplicationId id, String createUser, Date createTime) {
        this.id = id;
        this.createUser = createUser;
        this.createTime = createTime;
    }
    public AccountMappingApplication(AccountMappingApplicationId id, String createUser, Date createTime, String modifyUser, Date modifyTime, Date lastlogintime) {
       this.id = id;
       this.createUser = createUser;
       this.createTime = createTime;
       this.modifyUser = modifyUser;
       this.modifyTime = modifyTime;
       this.lastlogintime = lastlogintime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="accountId", column=@Column(name="account_id", nullable=false) ), 
        @AttributeOverride(name="appId", column=@Column(name="app_id", nullable=false) ) } )
    public AccountMappingApplicationId getId() {
        return this.id;
    }
    
    public void setId(AccountMappingApplicationId id) {
        this.id = id;
    }

    
    @Column(name="create_user", nullable=false)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=35)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="modify_user")
    public String getModifyUser() {
        return this.modifyUser;
    }
    
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modify_time", length=35)
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastlogintime", length=35)
    public Date getLastlogintime() {
        return this.lastlogintime;
    }
    
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }




}


