package com.elitech.gate.pojo;
// Generated Nov 1, 2017 1:46:10 PM by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ApplicationSetting generated by hbm2java
 */
@Entity
@Table(name="application_setting"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="app_id") 
)
public class ApplicationSetting  implements java.io.Serializable {


     private ApplicationSettingId id;
     private String appName;
     private String redirectUrl;
     private String createUser;
     private Date createTime;
     private String modifyUser;
     private Date modifyTime;

    public ApplicationSetting() {
    }

	
    public ApplicationSetting(ApplicationSettingId id, String appName, String redirectUrl, String createUser, Date createTime) {
        this.id = id;
        this.appName = appName;
        this.redirectUrl = redirectUrl;
        this.createUser = createUser;
        this.createTime = createTime;
    }
    public ApplicationSetting(ApplicationSettingId id, String appName, String redirectUrl, String createUser, Date createTime, String modifyUser, Date modifyTime) {
       this.id = id;
       this.appName = appName;
       this.redirectUrl = redirectUrl;
       this.createUser = createUser;
       this.createTime = createTime;
       this.modifyUser = modifyUser;
       this.modifyTime = modifyTime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="appId", column=@Column(name="app_id", unique=true, nullable=false) ), 
        @AttributeOverride(name="appKey", column=@Column(name="app_key", nullable=false) ) } )
    public ApplicationSettingId getId() {
        return this.id;
    }
    
    public void setId(ApplicationSettingId id) {
        this.id = id;
    }

    
    @Column(name="app_name", nullable=false)
    public String getAppName() {
        return this.appName;
    }
    
    public void setAppName(String appName) {
        this.appName = appName;
    }

    
    @Column(name="redirect_url", nullable=false)
    public String getRedirectUrl() {
        return this.redirectUrl;
    }
    
    public void setRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl;
    }

    
    @Column(name="create_user", nullable=false)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=35)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="modify_user")
    public String getModifyUser() {
        return this.modifyUser;
    }
    
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modify_time", length=35)
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }




}


