package com.elitech.gate.pojo;
// Generated Nov 1, 2017 1:46:10 PM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ApplicationSettingId generated by hbm2java
 */
@Embeddable
public class ApplicationSettingId  implements java.io.Serializable {


     private String appId;
     private String appKey;

    public ApplicationSettingId() {
    }

    public ApplicationSettingId(String appId, String appKey) {
       this.appId = appId;
       this.appKey = appKey;
    }
   


    @Column(name="app_id", unique=true, nullable=false)
    public String getAppId() {
        return this.appId;
    }
    
    public void setAppId(String appId) {
        this.appId = appId;
    }


    @Column(name="app_key", nullable=false)
    public String getAppKey() {
        return this.appKey;
    }
    
    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ApplicationSettingId) ) return false;
		 ApplicationSettingId castOther = ( ApplicationSettingId ) other; 
         
		 return ( (this.getAppId()==castOther.getAppId()) || ( this.getAppId()!=null && castOther.getAppId()!=null && this.getAppId().equals(castOther.getAppId()) ) )
 && ( (this.getAppKey()==castOther.getAppKey()) || ( this.getAppKey()!=null && castOther.getAppKey()!=null && this.getAppKey().equals(castOther.getAppKey()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAppId() == null ? 0 : this.getAppId().hashCode() );
         result = 37 * result + ( getAppKey() == null ? 0 : this.getAppKey().hashCode() );
         return result;
   }   


}


